import type { Category } from "@/types";

export const DEFAULT_CATEGORIES: Category[] = [
  // ─── Food & Drinks ───────────────────────────────────────────────────
  {
    id: "food_drinks",
    name: "Food & Drinks",
    icon: "🍽️",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["food", "eat", "meal", "hungry"],
  },
  {
    id: "tea_coffee",
    name: "Tea/Coffee",
    parentId: "food_drinks",
    icon: "☕",
    color: "#d97706",
    isDefault: true,
    type: "expense",
    keywords: ["chai", "tea", "coffee", "chaai", "chay", "cappuccino", "latte", "espresso"],
  },
  {
    id: "breakfast",
    name: "Breakfast",
    parentId: "food_drinks",
    icon: "🥞",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["breakfast", "nashta", "morning", "idli", "dosa", "paratha", "poha", "upma"],
  },
  {
    id: "lunch",
    name: "Lunch",
    parentId: "food_drinks",
    icon: "🍱",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["lunch", "दोपहर", "afternoon"],
  },
  {
    id: "dinner",
    name: "Dinner",
    parentId: "food_drinks",
    icon: "🍛",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["dinner", "supper", "रात", "raat"],
  },
  {
    id: "snacks",
    name: "Snacks",
    parentId: "food_drinks",
    icon: "🍟",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["snack", "chips", "biscuit", "namkeen", "maggi", "noodles", "samosa", "vada"],
  },
  {
    id: "restaurant",
    name: "Restaurant",
    parentId: "food_drinks",
    icon: "🍴",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["restaurant", "hotel", "cafe", "dhaba", "bistro", "zomato", "swiggy"],
  },
  {
    id: "delivery",
    name: "Delivery",
    parentId: "food_drinks",
    icon: "🛵",
    color: "#f59e0b",
    isDefault: true,
    type: "expense",
    keywords: ["delivery", "order", "online food"],
  },

  // ─── Transport ────────────────────────────────────────────────────────
  {
    id: "transport",
    name: "Transport",
    icon: "🚗",
    color: "#3b82f6",
    isDefault: true,
    type: "expense",
    keywords: ["travel", "commute", "fare"],
  },
  {
    id: "bus",
    name: "Bus",
    parentId: "transport",
    icon: "🚌",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["bus", "dtc", "bmtc", "ksrtc"],
  },
  {
    id: "auto",
    name: "Auto",
    parentId: "transport",
    icon: "🛺",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["auto", "autorickshaw", "rickshaw", "tuk"],
  },
  {
    id: "cab",
    name: "Cab",
    parentId: "transport",
    icon: "🚕",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["cab", "uber", "ola", "taxi", "rapido"],
  },
  {
    id: "fuel",
    name: "Fuel",
    parentId: "transport",
    icon: "⛽",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["fuel", "petrol", "diesel", "gas", "cng"],
  },
  {
    id: "train",
    name: "Train",
    parentId: "transport",
    icon: "🚂",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["train", "metro", "railway", "irctc", "local", "suburban"],
  },
  {
    id: "transport_other",
    name: "Other Transport",
    parentId: "transport",
    icon: "🚌",
    color: "#2563eb",
    isDefault: true,
    type: "expense",
    keywords: ["flight", "bus ticket", "ferry"],
  },

  // ─── Bills & Utilities ────────────────────────────────────────────────
  {
    id: "bills",
    name: "Bills & Utilities",
    icon: "📋",
    color: "#8b5cf6",
    isDefault: true,
    type: "expense",
    keywords: ["bill", "utility", "payment"],
  },
  {
    id: "mobile",
    name: "Mobile Recharge",
    parentId: "bills",
    icon: "📱",
    color: "#7c3aed",
    isDefault: true,
    type: "expense",
    keywords: ["recharge", "mobile", "phone", "jio", "airtel", "vi", "vodafone", "bsnl", "sim", "data"],
  },
  {
    id: "internet",
    name: "Internet",
    parentId: "bills",
    icon: "🌐",
    color: "#7c3aed",
    isDefault: true,
    type: "expense",
    keywords: ["internet", "wifi", "broadband", "fiber", "connection"],
  },
  {
    id: "electricity",
    name: "Electricity",
    parentId: "bills",
    icon: "⚡",
    color: "#7c3aed",
    isDefault: true,
    type: "expense",
    keywords: ["electricity", "bijli", "power", "electric", "eb", "bescom", "tata power"],
  },
  {
    id: "water",
    name: "Water",
    parentId: "bills",
    icon: "💧",
    color: "#7c3aed",
    isDefault: true,
    type: "expense",
    keywords: ["water", "paani", "jal"],
  },
  {
    id: "other_bills",
    name: "Other Bills",
    parentId: "bills",
    icon: "📋",
    color: "#7c3aed",
    isDefault: true,
    type: "expense",
    keywords: ["bill", "subscription", "netflix", "amazon", "hotstar", "spotify"],
  },

  // ─── Home ─────────────────────────────────────────────────────────────
  {
    id: "home",
    name: "Home",
    icon: "🏠",
    color: "#10b981",
    isDefault: true,
    type: "expense",
    keywords: ["home", "house", "ghar"],
  },
  {
    id: "rent",
    name: "Rent",
    parentId: "home",
    icon: "🏘️",
    color: "#059669",
    isDefault: true,
    type: "expense",
    keywords: ["rent", "kiraya", "house rent", "pg", "accommodation"],
  },
  {
    id: "household",
    name: "Household",
    parentId: "home",
    icon: "🏡",
    color: "#059669",
    isDefault: true,
    type: "expense",
    keywords: ["household", "home maintenance", "repair", "cleaning", "maid", "bai"],
  },
  {
    id: "groceries",
    name: "Groceries",
    parentId: "home",
    icon: "🛒",
    color: "#059669",
    isDefault: true,
    type: "expense",
    keywords: ["grocery", "groceries", "vegetables", "sabzi", "fruits", "sabzi", "market", "kirana", "sabjiswala"],
  },

  // ─── Personal ─────────────────────────────────────────────────────────
  {
    id: "personal",
    name: "Personal",
    icon: "👤",
    color: "#ec4899",
    isDefault: true,
    type: "expense",
    keywords: ["personal"],
  },
  {
    id: "shopping",
    name: "Shopping",
    parentId: "personal",
    icon: "🛍️",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["shopping", "shop", "buy", "purchase", "amazon", "flipkart", "meesho", "myntra"],
  },
  {
    id: "clothes",
    name: "Clothes",
    parentId: "personal",
    icon: "👕",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["clothes", "shirt", "pant", "kurta", "dress", "jeans", "trouser", "jacket", "shoes", "footwear", "saree", "salwar", "suit"],
  },
  {
    id: "personal_care",
    name: "Personal Care",
    parentId: "personal",
    icon: "💇",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["haircut", "salon", "parlour", "shave", "barber", "hair", "beauty", "cosmetics", "cream", "shampoo"],
  },
  {
    id: "gym",
    name: "Gym",
    parentId: "personal",
    icon: "🏋️",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["gym", "fitness", "yoga", "workout", "exercise"],
  },
  {
    id: "medical",
    name: "Medical",
    parentId: "personal",
    icon: "💊",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["medical", "medicine", "doctor", "hospital", "clinic", "pharmacy", "health", "tablet", "injection"],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    parentId: "personal",
    icon: "🎬",
    color: "#db2777",
    isDefault: true,
    type: "expense",
    keywords: ["movie", "cinema", "film", "show", "concert", "event", "ticket", "game", "park", "fun", "entertainment"],
  },

  // ─── Financial ────────────────────────────────────────────────────────
  {
    id: "financial",
    name: "Financial",
    icon: "💰",
    color: "#64748b",
    isDefault: true,
    type: "both",
    keywords: ["finance", "money"],
  },
  {
    id: "emi",
    name: "EMI",
    parentId: "financial",
    icon: "🏦",
    color: "#475569",
    isDefault: true,
    type: "expense",
    keywords: ["emi", "loan emi", "installment", "kist"],
  },
  {
    id: "investment",
    name: "Investment",
    parentId: "financial",
    icon: "📈",
    color: "#475569",
    isDefault: true,
    type: "expense",
    keywords: ["investment", "invest", "mutual fund", "sip", "stocks", "shares", "fd", "ppf", "nps"],
  },
  {
    id: "savings",
    name: "Savings",
    parentId: "financial",
    icon: "🏧",
    color: "#475569",
    isDefault: true,
    type: "expense",
    keywords: ["savings", "save", "saving"],
  },
  {
    id: "bank_charges",
    name: "Bank Charges",
    parentId: "financial",
    icon: "🏛️",
    color: "#475569",
    isDefault: true,
    type: "expense",
    keywords: ["bank charge", "bank fee", "atm charge", "transaction charge"],
  },

  // ─── People ───────────────────────────────────────────────────────────
  {
    id: "people",
    name: "People",
    icon: "👥",
    color: "#f97316",
    isDefault: true,
    type: "both",
    keywords: ["person", "people"],
  },
  {
    id: "family",
    name: "Family",
    parentId: "people",
    icon: "👨‍👩‍👧‍👦",
    color: "#ea580c",
    isDefault: true,
    type: "both",
    keywords: ["family", "mummy", "papa", "mom", "dad", "mother", "father", "brother", "sister", "bhai", "didi", "bhaiya", "aai", "baba"],
  },
  {
    id: "friend",
    name: "Friend",
    parentId: "people",
    icon: "👫",
    color: "#ea580c",
    isDefault: true,
    type: "both",
    keywords: ["friend", "dost", "yaar"],
  },
  {
    id: "loan_given",
    name: "Loan Given",
    parentId: "people",
    icon: "↗️",
    color: "#ea580c",
    isDefault: true,
    type: "expense",
    keywords: ["gave", "given", "lend", "lent", "borrowed to"],
  },
  {
    id: "loan_received",
    name: "Loan Received",
    parentId: "people",
    icon: "↙️",
    color: "#ea580c",
    isDefault: true,
    type: "income",
    keywords: ["borrowed", "borrow", "received from", "got from"],
  },

  // ─── Income ───────────────────────────────────────────────────────────
  {
    id: "salary",
    name: "Salary",
    icon: "💼",
    color: "#22c55e",
    isDefault: true,
    type: "income",
    keywords: ["salary", "stipend", "pay", "wage", "income", "ctc", "paycheck"],
  },
  {
    id: "freelance",
    name: "Freelance",
    icon: "💻",
    color: "#22c55e",
    isDefault: true,
    type: "income",
    keywords: ["freelance", "project", "client", "consulting"],
  },
  {
    id: "refund",
    name: "Refund",
    icon: "↩️",
    color: "#22c55e",
    isDefault: true,
    type: "income",
    keywords: ["refund", "cashback", "return", "reversal", "reimbursement", "reimburse"],
  },
  {
    id: "other_income",
    name: "Other Income",
    icon: "💵",
    color: "#22c55e",
    isDefault: true,
    type: "income",
    keywords: ["dividend", "interest", "rental income", "other income"],
  },

  // ─── Other ────────────────────────────────────────────────────────────
  {
    id: "other",
    name: "Other",
    icon: "📦",
    color: "#94a3b8",
    isDefault: true,
    type: "both",
    keywords: ["misc", "miscellaneous", "other"],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return DEFAULT_CATEGORIES.find((c) => c.id === id);
}

export function getTopLevelCategories(): Category[] {
  return DEFAULT_CATEGORIES.filter((c) => !c.parentId);
}

export function getSubCategories(parentId: string): Category[] {
  return DEFAULT_CATEGORIES.filter((c) => c.parentId === parentId);
}
