import type { Transaction, LoanRecord, Budget, RecurringTransaction } from "@/types";
import { generateId, getCurrentDate } from "./utils";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function ts(): string {
  return new Date().toISOString();
}

export const DEMO_TRANSACTIONS: Transaction[] = [
  // Today
  {
    id: generateId(),
    type: "expense",
    amount: 15,
    description: "Chai",
    categoryId: "tea_coffee",
    date: getCurrentDate(),
    time: "08:30",
    paymentMethod: "cash",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 50,
    description: "Auto to office",
    categoryId: "auto",
    date: getCurrentDate(),
    time: "09:15",
    paymentMethod: "cash",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 180,
    description: "Dinner",
    categoryId: "dinner",
    date: getCurrentDate(),
    time: "21:00",
    paymentMethod: "upi",
    createdAt: ts(),
    updatedAt: ts(),
  },
  // Yesterday
  {
    id: generateId(),
    type: "expense",
    amount: 120,
    description: "Lunch at office",
    categoryId: "lunch",
    date: daysAgo(1),
    time: "13:30",
    paymentMethod: "upi",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 500,
    description: "Petrol",
    categoryId: "fuel",
    date: daysAgo(1),
    time: "18:00",
    paymentMethod: "upi",
    createdAt: ts(),
    updatedAt: ts(),
  },
  // This month
  {
    id: generateId(),
    type: "income",
    amount: 29000,
    description: "Salary",
    categoryId: "salary",
    date: daysAgo(5),
    time: "10:00",
    paymentMethod: "bank_transfer",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 8000,
    description: "Rent",
    categoryId: "rent",
    date: daysAgo(4),
    time: "11:00",
    paymentMethod: "bank_transfer",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "money_given",
    amount: 5000,
    description: "Given to Mummy",
    categoryId: "family",
    date: daysAgo(3),
    time: "12:00",
    paymentMethod: "cash",
    person: "Mummy",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 299,
    description: "Jio Recharge",
    categoryId: "mobile",
    date: daysAgo(6),
    time: "10:30",
    paymentMethod: "upi",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 350,
    description: "Groceries",
    categoryId: "groceries",
    date: daysAgo(7),
    time: "19:00",
    paymentMethod: "cash",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 250,
    description: "Movie tickets",
    categoryId: "entertainment",
    date: daysAgo(8),
    time: "17:00",
    paymentMethod: "credit_card",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "expense",
    amount: 2000,
    description: "EMI",
    categoryId: "emi",
    date: daysAgo(5),
    time: "09:00",
    paymentMethod: "bank_transfer",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "income",
    amount: 500,
    description: "Refund from Amazon",
    categoryId: "refund",
    date: daysAgo(2),
    time: "14:00",
    paymentMethod: "bank_transfer",
    createdAt: ts(),
    updatedAt: ts(),
  },
];

export const DEMO_LOANS: LoanRecord[] = [
  {
    id: generateId(),
    personName: "Rahul",
    direction: "given",
    principalAmount: 2000,
    paidAmount: 500,
    date: daysAgo(10),
    status: "partially_paid",
    notes: "For his travel",
    relatedTransactionIds: [],
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    personName: "Ankit",
    direction: "received",
    principalAmount: 1000,
    paidAmount: 0,
    date: daysAgo(15),
    status: "pending",
    notes: "For emergency",
    relatedTransactionIds: [],
    createdAt: ts(),
    updatedAt: ts(),
  },
];

export const DEMO_BUDGETS: Budget[] = [
  {
    id: generateId(),
    name: "Monthly Budget",
    amount: 20000,
    period: "monthly",
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    name: "Food Budget",
    amount: 5000,
    categoryId: "food_drinks",
    period: "monthly",
    createdAt: ts(),
    updatedAt: ts(),
  },
];

export const DEMO_RECURRING: RecurringTransaction[] = [
  {
    id: generateId(),
    type: "expense",
    amount: 8000,
    description: "Rent",
    categoryId: "rent",
    paymentMethod: "bank_transfer",
    frequency: "monthly",
    startDate: daysAgo(30),
    isActive: true,
    createdAt: ts(),
    updatedAt: ts(),
  },
  {
    id: generateId(),
    type: "income",
    amount: 29000,
    description: "Salary",
    categoryId: "salary",
    paymentMethod: "bank_transfer",
    frequency: "monthly",
    startDate: daysAgo(30),
    isActive: true,
    createdAt: ts(),
    updatedAt: ts(),
  },
];
